[project]
name = "placeholder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "game-state>=2.3.0",
    "kraken-engine>=1.4.1",
]
